sudo: required

services:
   - docker

install:
   - docker run --rm --privileged multiarch/qemu-user-static:register --reset
   
script:
   - chmod 755 ./build.sh
   - docker run --rm -v ${PWD}/build.sh:/tmp/build.sh $DOCKER_IMAGE_NAME /tmp/build.sh

env:
   - DOCKER_IMAGE_NAME=jsurf/rpi-raspbian-build-essentials:latest
